title: Library data storytelling
author: Libraries Hacked
email: info@librarieshacked.org
description: Telling stories with library data
url: "https://www.librarystorytelling.net"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Hard work always pays off
  avatar_url:
  date_format: "%b %-d, %Y"
  back_to: "Index"
  social_links:
    rss: RSS
    github: librarieshacked
    facebook:
    linkedin: librarieshacked
