# Site settings
title: Library storytelling
description: "Telling stories with library data"
baseurl: "/"
url: "https://www.librarystorytelling.net"

remote_theme: chesterhow/tale

# Umami Analytics
google_analytics: 83e3b0d3-1f59-46af-8196-b6790af8d38f

# Author
author:
  name: Dave Rowe
  url: https://www.davesrowe.co.uk
  email: info@librarieshacked.org

# Build settings
markdown: kramdown
include:
  - _pages

permalink: /:title
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]
