title: Library data storytelling
author: Essential information about data storytelling
email: info@librarieshacked.org
description: Telling stories with library data
url: "https://www.librarystorytelling.net"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Library data storytelling is a project to promote and celebrate libraries by using library data to tell compelling stories
  avatar_url:
  date_format: "%b %-d, %Y"
  back_to: "Home"
  social_links:
    rss: RSS
    github:
    facebook:
    linkedin:
