# Site settings
title: Library Storytelling
description: "Telling stories with library data"
baseurl: "/"
url: "https://www.librarystorytelling.net"

remote_theme: chesterhow/tale

# Google Analytics
google_analytics:

# Author
author:
  name: Dave Rowe
  url: https://www.davesrowe.co.uk
  email:

# Build settings
markdown: kramdown
include:
  - _pages

permalink: /:year-:month-:day/:title
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Excludes
exclude: [Gemfile, Gemfile.lock, tale.gemspec]
